### ISSUE TITLE
AppVeyor NuGet version issue

### ISSUE THREAD

**Issue by NetChris** [NetChris/NetChris.Owin.Hsts#9]
See https://ci.appveyor.com/project/NetChris/netchris-identity/build/0.0.27/job/udy11xyclgpuqwv6

* A NuGet package that AppVeyor builds will be available on its project feed.
  * This is not avoidable.  If the package is built, it'll be in the feed.
  * The package _must_ be built in order to use it as an artifact for deployment to NuGet (or any other external NuGet feed)

**Comment by NetChris** [comment]
See http://help.appveyor.com/discussions/problems/1612-semver-metadata-not-supported-in-assembly-info-patching

**Comment by NetChris** [comment]
What about:
* Abandon the SemVer job
* Patching only the informational version
* Providing an optional environment variable to tack onto prerelease versions

```yml
version: 1.1.{build}

environment:
  prerelease: "-pr"

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_informational_version: '{version}{prerelease}'

os: Visual Studio 2015
configuration: Release
init:
- cmd: set BuildNumber=%APPVEYOR_BUILD_NUMBER%
nuget:
  account_feed: true
before_build:
- cmd: >-
    nuget restore "src\NetChris.Owin.Hsts.sln"
    msbuild SemVer.proj /T:SemVer
build:
  project: src\NetChris.Owin.Hsts.sln
  publish_nuget: true
  verbosity: normal

deploy:
  provider: Environment
  name: nuggetboy.nuget.org
  on:
    branch: master
    Configuration: Release
```
